version: '2'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "80:5000"
    volumes:
      - .:/code

  web2:
    build: ./another_WS
    command: python ./another_WS/dog_shelter.py
    ports:
      - "81:5000"
    depends_on:
      - web
    volumes:
      - .:/code
